name: Run ETL Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite rodar manualmente pelo painel do GitHub

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas google-cloud-bigquery python-dotenv gcsfs pyarrow db-dtypes functions-framework

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy Main ETL to Cloud Functions
      id: deploy-main
      uses: google-github-actions/deploy-cloud-functions@v3
      with:
        name: localiza-etl-pipeline
        runtime: python311
        region: us-east1
        source_dir: ./src
        entry_point: run_etl_cf

    - name: Deploy Gold Tabela 1 to Cloud Functions
      id: deploy-gold-1
      uses: google-github-actions/deploy-cloud-functions@v3
      with:
        name: gold_tabela_1
        runtime: python311
        region: us-east1
        source_dir: ./src
        entry_point: run_gold_tabela_1_cf

    - name: Deploy Gold Tabela 2 to Cloud Functions
      id: deploy-gold-2
      uses: google-github-actions/deploy-cloud-functions@v3
      with:
        name: gold_tabela_2
        runtime: python311
        region: us-east1
        source_dir: ./src
        entry_point: run_gold_tabela_2_cf
